### PR TITLE
Fix variance-covariance input

### PR DESCRIPTION
**Pull request by Kucharssim**
fixes https://github.com/jasp-stats/jasp-issues/issues/1845

### CODE REVIEW

**Review by juliuspf — APPROVED** [review]
This all looks good. I wonder if there can be something done about the sample size field. It is currently set to 0 which leads to an error message when first choosing the varcov matrix as input. Maybe that field could be highlighted better? But since this has nothing to do with the current changes, you can also leave all as is.

**Comment by Kucharssim** [comment]
> I wonder if there can be something done about the sample size field. It is currently set to 0 which leads to an error message when first choosing the varcov matrix as input.

We could change it to be always strictly positive (with a default of 1), even though I am not sure whether that makes it much better.

> Maybe that field could be highlighted better?

What would you have in mind?

**Comment by juliuspf** [comment]
Well I think this will be tricky in qml, but as soon as one chooses the varcov as input, the sample size field could get a red box....
Screenshot 2022-11-11 at 10 04 36
something like this, but the red box would only appear once you selected the varcov button.

**Comment by Kucharssim** [comment]
That would make it clearer indeed. @boutinb, how could we do this?

**Comment by Kucharssim** [comment]
If there is no time to look into the QML issue, I guess we can also merge this and make a new issue for that. Any thoughts @boutinb?

**Comment by Kucharssim** [comment]
I'll merge this for now and make an issue for the QML part for later...

**Pull request merged**
