### PR TITLE
fix path plot with ordered variables

### PR DESCRIPTION
**Pull request by Kucharssim**
fixes https://github.com/jasp-stats/jasp-issues/issues/1629
fixes https://github.com/jasp-stats/jasp-issues/issues/1617
fixes https://github.com/jasp-stats/jasp-issues/issues/1918

For background also see 
- https://github.com/jasp-stats/jaspSem/pull/16
- https://github.com/jasp-stats/jaspFactor/pull/69

### CODE REVIEW

**Review by juliuspf — APPROVED** [review]
Nice. The error is gone. The path plot is displayed. I think for the future, we should also display the thresholds in a table? Also, I am having trouble understanding how the thresholds are displayed in the path diagram: 
Screenshot 2022-11-29 at 14 44 31

**Comment by Kucharssim** [comment]
>  we should also display the thresholds in a table?

Yes, I'll make an issue for that.

>  I am having trouble understanding how the thresholds are displayed in the path diagram

From the documentation of `semPlot`:

> Thresholds are displayed as small lines inside of the manifest nodes

I agree that this does not look particularly well, we can also fiddle with the settings of `semPlot` to improve it (or disable drawing thresholds completely).

**Comment by juliuspf** [comment]
Hmm, I would be fine with disabling them and adding a table at a later stage within one new PR then? So you can merge if you like.

**Comment by Kucharssim** [comment]
I made an issue collecting the output of our discussion about this. Will merge this for now.

**Pull request merged**
